<a href="https://colab.research.google.com/github/Mao925/Natural-Language-Processing-with-disaster-tweets/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# =========================
# 1. CSVファイルの読み込み
# =========================

train_path = "/content/drive/MyDrive/Kaggle/NLP/train.csv"
test_path  = "/content/drive/MyDrive/Kaggle/NLP/test.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

print("読み込み完了")
print("train shape:", train.shape)
print("test shape :", test.shape)


# =========================
# 2. 先頭データの確認
# =========================

print("\n===== train head =====")
display(train.head())

print("\n===== test head =====")
display(test.head())


# =========================
# 3. カラム一覧の確認
# =========================

print("\n===== train columns =====")
print(train.columns.tolist())

print("\n===== test columns =====")
print(test.columns.tolist())


# =========================
# 4. データ型・欠損値の確認
# =========================

print("\n===== train info =====")
train.info()

print("\n===== test info =====")
test.info()

print("\n===== train missing values =====")
display(train.isnull().sum().sort_values(ascending=False))

print("\n===== test missing values =====")
display(test.isnull().sum().sort_values(ascending=False))


# =========================
# 5. 重複行の確認
# =========================

print("\n===== duplicated rows =====")
print("train duplicated:", train.duplicated().sum())
print("test duplicated :", test.duplicated().sum())


# =========================
# 6. 数値データの統計量
# =========================

print("\n===== train describe numerical =====")
display(train.describe())

print("\n===== test describe numerical =====")
display(test.describe())


# =========================
# 7. 文字列カラムの確認
# =========================

text_cols_train = train.select_dtypes(include="object").columns.tolist()
text_cols_test = test.select_dtypes(include="object").columns.tolist()

print("\n===== object columns =====")
print("train object columns:", text_cols_train)
print("test object columns :", text_cols_test)

for col in text_cols_train:
    print(f"\n===== train: {col} sample =====")
    display(train[col].head(10))
    print("文字数の統計:")
    display(train[col].astype(str).str.len().describe())


# =========================
# 8. 目的変数っぽいカラムの分布確認
# =========================

possible_target_cols = ["target", "label", "class", "sentiment", "y"]

for col in possible_target_cols:
    if col in train.columns:
        print(f"\n===== target distribution: {col} =====")
        display(train[col].value_counts())
        display(train[col].value_counts(normalize=True))

読み込み完了
train shape: (7613, 5)
test shape : (3263, 4)

===== train head =====

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

===== test head =====

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

===== train columns =====
['id', 'keyword', 'location', 'text', 'target']

===== test columns =====
['id', 'keyword', 'location', 'text']

===== train info =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

===== test info =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3263 non-null   int64
 1   keyword   3237 non-null   object
 2   location  2158 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB

===== train missing values =====

location    2533
keyword       61
id             0
text           0
target         0
dtype: int64

===== test missing values =====

location    1105
keyword       26
id             0
text           0
dtype: int64

===== duplicated rows =====
train duplicated: 0
test duplicated : 0

===== train describe numerical =====

                 id      target
count   7613.000000  7613.00000
mean    5441.934848     0.42966
std     3137.116090     0.49506
min        1.000000     0.00000
25%     2734.000000     0.00000
50%     5408.000000     0.00000
75%     8146.000000     1.00000
max    10873.000000     1.00000

===== test describe numerical =====

                 id
count   3263.000000
mean    5427.152927
std     3146.427221
min        0.000000
25%     2683.000000
50%     5500.000000
75%     8176.000000
max    10875.000000

===== object columns =====
train object columns: ['keyword', 'location', 'text']
test object columns : ['keyword', 'location', 'text']

===== train: keyword sample =====

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: keyword, dtype: object

文字数の統計:

count    7613.000000
mean        8.691186
std         3.484878
min         3.000000
25%         6.000000
50%         8.000000
75%        10.000000
max        21.000000
Name: keyword, dtype: float64

===== train: location sample =====

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: location, dtype: object

文字数の統計:

count    7613.000000
mean       10.103639
std         7.651339
min         1.000000
25%         3.000000
50%         8.000000
75%        15.000000
max        49.000000
Name: location, dtype: float64

===== train: text sample =====

0    Our Deeds are the Reason of this #earthquake M...
1               Forest fire near La Ronge Sask. Canada
2    All residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    Just got sent this photo from Ruby #Alaska as ...
5    #RockyFire Update => California Hwy. 20 closed...
6    #flood #disaster Heavy rain causes flash flood...
7    I'm on top of the hill and I can see a fire in...
8    There's an emergency evacuation happening now ...
9    I'm afraid that the tornado is coming to our a...
Name: text, dtype: object

文字数の統計:

count    7613.000000
mean      101.037436
std        33.781325
min         7.000000
25%        78.000000
50%       107.000000
75%       133.000000
max       157.000000
Name: text, dtype: float64

===== target distribution: target =====

target
0    4342
1    3271
Name: count, dtype: int64

target
0    0.57034
1    0.42966
Name: proportion, dtype: float64

In [3]:
import pandas as pd
import re
import html
from urllib.parse import unquote

# =========================
# 1. CSVファイルの読み込み
# =========================

train_path = "/content/drive/MyDrive/Kaggle/NLP/train.csv"
test_path = "/content/drive/MyDrive/Kaggle/NLP/test.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

print("読み込み完了")
print("train shape:", train.shape)
print("test shape :", test.shape)


# =========================
# 2. 必要カラムの確認
# =========================

required_train_cols = ["id", "keyword", "location", "text", "target"]
required_test_cols = ["id", "keyword", "location", "text"]

missing_train_cols = [col for col in required_train_cols if col not in train.columns]
missing_test_cols = [col for col in required_test_cols if col not in test.columns]

if missing_train_cols:
    raise ValueError(f"train.csvに存在しないカラムがあります: {missing_train_cols}")

if missing_test_cols:
    raise ValueError(f"test.csvに存在しないカラムがあります: {missing_test_cols}")


# =========================
# 3. 軽いテキストクリーニング関数
# =========================

def clean_text_for_tfidf(text):
    """
    TF-IDF + LogisticRegression向けの軽いクリーニング。
    過剰な正規化はせず、単語情報をできるだけ残す。
    """
    if pd.isna(text):
        return ""

    text = str(text)

    # HTMLエスケープを戻す
    text = html.unescape(text)

    # URLエンコードを戻す
    # 例: body%20bags -> body bags
    text = unquote(text)

    # 小文字化
    text = text.lower()

    # URLを <url> に置換
    text = re.sub(r"https?://\S+|www\.\S+", " <url> ", text)

    # メンションを <user> に置換
    text = re.sub(r"@\w+", " <user> ", text)

    # ハッシュタグは # だけ削除して単語は残す
    text = re.sub(r"#", "", text)

    # 連続する空白を1つにまとめる
    text = re.sub(r"\s+", " ", text)

    # 前後の空白を削除
    text = text.strip()

    return text


# =========================
# 4. train / test に同じ前処理を適用
# =========================

train_processed = train.copy()
test_processed = test.copy()

# keywordの欠損値は空文字で補完
train_processed["keyword"] = train_processed["keyword"].fillna("")
test_processed["keyword"] = test_processed["keyword"].fillna("")

# textにも念のため欠損対応
train_processed["text"] = train_processed["text"].fillna("")
test_processed["text"] = test_processed["text"].fillna("")

# keywordとtextをクリーニング
train_processed["keyword_clean"] = train_processed["keyword"].apply(clean_text_for_tfidf)
test_processed["keyword_clean"] = test_processed["keyword"].apply(clean_text_for_tfidf)

train_processed["text_clean"] = train_processed["text"].apply(clean_text_for_tfidf)
test_processed["text_clean"] = test_processed["text"].apply(clean_text_for_tfidf)

# keyword_clean と text_clean を結合して input_text を作成
train_processed["input_text"] = (
    train_processed["keyword_clean"] + " " + train_processed["text_clean"]
).str.strip()

test_processed["input_text"] = (
    test_processed["keyword_clean"] + " " + test_processed["text_clean"]
).str.strip()


# =========================
# 5. 確認
# =========================

print("\n===== train_processed head =====")
display(train_processed.head())

print("\n===== test_processed head =====")
display(test_processed.head())

print("\n===== train_processed missing values =====")
display(train_processed.isnull().sum().sort_values(ascending=False))

print("\n===== test_processed missing values =====")
display(test_processed.isnull().sum().sort_values(ascending=False))

print("\n===== input_text samples: train =====")
display(train_processed[["id", "keyword", "keyword_clean", "text", "text_clean", "input_text", "target"]].head(10))

print("\n===== input_text samples: test =====")
display(test_processed[["id", "keyword", "keyword_clean", "text", "text_clean", "input_text"]].head(10))

print("\n===== target distribution =====")
display(train_processed["target"].value_counts())
display(train_processed["target"].value_counts(normalize=True))

print("\n前処理完了")
print("train_processed shape:", train_processed.shape)
print("test_processed shape :", test_processed.shape)

読み込み完了
train shape: (7613, 5)
test shape : (3263, 4)

===== train_processed head =====

,id,keyword,location,text,target,keyword_clean,text_clean,input_text
0,1,,NaN,Our Deeds are the Reason of this #earthquake M...,1,,our deeds are the reason of this earthquake ma...,our deeds are the reason of this earthquake ma...
1,4,,NaN,Forest fire near La Ronge Sask. Canada,1,,forest fire near la ronge sask. canada,forest fire near la ronge sask. canada
2,5,,NaN,All residents asked to 'shelter in place' are ...,1,,all residents asked to 'shelter in place' are ...,all residents asked to 'shelter in place' are ...
3,6,,NaN,"13,000 people receive #wildfires evacuation or...",1,,"13,000 people receive wildfires evacuation ord...","13,000 people receive wildfires evacuation ord..."
4,7,,NaN,Just got sent this photo from Ruby #Alaska as ...,1,,just got sent this photo from ruby alaska as s...,just got sent this photo from ruby alaska as s...

===== test_processed head =====

,id,keyword,location,text,keyword_clean,text_clean,input_text
0,0,,NaN,Just happened a terrible car crash,,just happened a terrible car crash,just happened a terrible car crash
1,2,,NaN,"Heard about #earthquake is different cities, s...",,"heard about earthquake is different cities, st...","heard about earthquake is different cities, st..."
2,3,,NaN,"there is a forest fire at spot pond, geese are...",,"there is a forest fire at spot pond, geese are...","there is a forest fire at spot pond, geese are..."
3,9,,NaN,Apocalypse lighting. #Spokane #wildfires,,apocalypse lighting. spokane wildfires,apocalypse lighting. spokane wildfires
4,11,,NaN,Typhoon Soudelor kills 28 in China and Taiwan,,typhoon soudelor kills 28 in china and taiwan,typhoon soudelor kills 28 in china and taiwan

===== train_processed missing values =====

location         2533
id                  0
keyword             0
text                0
target              0
keyword_clean       0
text_clean          0
input_text          0
dtype: int64

===== test_processed missing values =====

location         1105
id                  0
keyword             0
text                0
keyword_clean       0
text_clean          0
input_text          0
dtype: int64

===== input_text samples: train =====

,id,keyword,keyword_clean,text,text_clean,input_text,target
0,1,,,Our Deeds are the Reason of this #earthquake M...,our deeds are the reason of this earthquake ma...,our deeds are the reason of this earthquake ma...,1
1,4,,,Forest fire near La Ronge Sask. Canada,forest fire near la ronge sask. canada,forest fire near la ronge sask. canada,1
2,5,,,All residents asked to 'shelter in place' are ...,all residents asked to 'shelter in place' are ...,all residents asked to 'shelter in place' are ...,1
3,6,,,"13,000 people receive #wildfires evacuation or...","13,000 people receive wildfires evacuation ord...","13,000 people receive wildfires evacuation ord...",1
4,7,,,Just got sent this photo from Ruby #Alaska as ...,just got sent this photo from ruby alaska as s...,just got sent this photo from ruby alaska as s...,1
5,8,,,#RockyFire Update => California Hwy. 20 closed...,rockyfire update => california hwy. 20 closed ...,rockyfire update => california hwy. 20 closed ...,1
6,10,,,#flood #disaster Heavy rain causes flash flood...,flood disaster heavy rain causes flash floodin...,flood disaster heavy rain causes flash floodin...,1
7,13,,,I'm on top of the hill and I can see a fire in...,i'm on top of the hill and i can see a fire in...,i'm on top of the hill and i can see a fire in...,1
8,14,,,There's an emergency evacuation happening now ...,there's an emergency evacuation happening now ...,there's an emergency evacuation happening now ...,1
9,15,,,I'm afraid that the tornado is coming to our a...,i'm afraid that the tornado is coming to our a...,i'm afraid that the tornado is coming to our a...,1

===== input_text samples: test =====

,id,keyword,keyword_clean,text,text_clean,input_text
0,0,,,Just happened a terrible car crash,just happened a terrible car crash,just happened a terrible car crash
1,2,,,"Heard about #earthquake is different cities, s...","heard about earthquake is different cities, st...","heard about earthquake is different cities, st..."
2,3,,,"there is a forest fire at spot pond, geese are...","there is a forest fire at spot pond, geese are...","there is a forest fire at spot pond, geese are..."
3,9,,,Apocalypse lighting. #Spokane #wildfires,apocalypse lighting. spokane wildfires,apocalypse lighting. spokane wildfires
4,11,,,Typhoon Soudelor kills 28 in China and Taiwan,typhoon soudelor kills 28 in china and taiwan,typhoon soudelor kills 28 in china and taiwan
5,12,,,We're shaking...It's an earthquake,we're shaking...it's an earthquake,we're shaking...it's an earthquake
6,21,,,They'd probably still show more life than Arse...,they'd probably still show more life than arse...,they'd probably still show more life than arse...
7,22,,,Hey! How are you?,hey! how are you?,hey! how are you?
8,27,,,What a nice hat?,what a nice hat?,what a nice hat?
9,29,,,Fuck off!,fuck off!,fuck off!

===== target distribution =====

target
0    4342
1    3271
Name: count, dtype: int64

target
0    0.57034
1    0.42966
Name: proportion, dtype: float64

前処理完了
train_processed shape: (7613, 8)
test_processed shape : (3263, 7)

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# =========================
# 1. 使用するデータの準備
# =========================

# 前処理済みの input_text を使用
X = train_processed["input_text"].fillna("")
y = train_processed["target"].astype(int)

X_test = test_processed["input_text"].fillna("")

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)

print("\n===== target distribution =====")
display(y.value_counts())
display(y.value_counts(normalize=True))


# =========================
# 2. 学習用データ / 検証用データに分割
# =========================

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("\n===== split result =====")
print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)
print("y_train:", y_train.shape)
print("y_valid:", y_valid.shape)


# =========================
# 3. TF-IDF + LogisticRegression Pipeline
# =========================

model = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            ngram_range=(1, 2),
            min_df=2,
            max_df=0.95,
            sublinear_tf=True
        )
    ),
    (
        "logreg",
        LogisticRegression(
            max_iter=1000,
            C=1.0,
            random_state=42
        )
    )
])


# =========================
# 4. モデル学習
# =========================

model.fit(X_train, y_train)

print("\n学習完了")


# =========================
# 5. 検証データで予測
# =========================

valid_pred = model.predict(X_valid)

accuracy = accuracy_score(y_valid, valid_pred)
f1 = f1_score(y_valid, valid_pred)

print("\n===== validation score =====")
print("accuracy:", accuracy)
print("f1_score:", f1)

print("\n===== classification report =====")
print(classification_report(y_valid, valid_pred))

print("\n===== confusion matrix =====")
cm = confusion_matrix(y_valid, valid_pred)
cm_df = pd.DataFrame(
    cm,
    index=["actual_0", "actual_1"],
    columns=["pred_0", "pred_1"]
)
display(cm_df)


# =========================
# 6. testデータに対して予測
# =========================

test_pred = model.predict(X_test)

print("\n===== test prediction distribution =====")
display(pd.Series(test_pred).value_counts())
display(pd.Series(test_pred).value_counts(normalize=True))


# =========================
# 7. Kaggle提出用CSVを作成
# =========================

submission = pd.DataFrame({
    "id": test_processed["id"],
    "target": test_pred.astype(int)
})

submission_path = "submission_tfidf_logreg.csv"
submission.to_csv(submission_path, index=False)

print("\n提出用CSVを作成しました:", submission_path)

print("\n===== submission head =====")
display(submission.head())

print("\n===== submission shape =====")
print(submission.shape)


# =========================
# 8. 改善候補メモ
# =========================

# 改善候補1:
# char-level TF-IDFを追加する
# 例: analyzer="char_wb", ngram_range=(3, 5)
#
# 改善候補2:
# LogisticRegressionのCを調整する
# 例: C=0.5, 1.0, 2.0, 3.0 など
#
# 改善候補3:
# class_weight="balanced" を試す
#
# 改善候補4:
# word TF-IDF と char TF-IDF を FeatureUnion で結合する

X shape: (7613,)
y shape: (7613,)
X_test shape: (3263,)

===== target distribution =====

target
0    4342
1    3271
Name: count, dtype: int64

target
0    0.57034
1    0.42966
Name: proportion, dtype: float64

===== split result =====
X_train: (6090,)
X_valid: (1523,)
y_train: (6090,)
y_valid: (1523,)

学習完了

===== validation score =====
accuracy: 0.8102429415627052
f1_score: 0.7633087633087633

===== classification report =====
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       869
           1       0.82      0.71      0.76       654

    accuracy                           0.81      1523
   macro avg       0.81      0.80      0.80      1523
weighted avg       0.81      0.81      0.81      1523


===== confusion matrix =====

          pred_0  pred_1
actual_0     768     101
actual_1     188     466

===== test prediction distribution =====

0    2125
1    1138
Name: count, dtype: int64

0    0.651241
1    0.348759
Name: proportion, dtype: float64

提出用CSVを作成しました: submission_tfidf_logreg.csv

===== submission head =====

   id  target
0   0       1
1   2       0
2   3       1
3   9       0
4  11       1

===== submission shape =====
(3263, 2)